### ISSUE TITLE
第19节中的错误

### ISSUE THREAD

**Issue by cocobear** [chusiang/automate-with-ansible#38]
-- tasks/：將各種不同任務獨立出來的 tasks，在裡分別為 restart_api.yml, **restart_api**.yml, setting_nginx.yml 和 setup.yml。

++ tasks/：將各種不同任務獨立出來的 tasks，在裡分別為 restart_api.yml, **setting_api**.yml, setting_nginx.yml 和 setup.yml。

**Comment by chusiang** [comment]
已修正，感謝 feedback。👍
